services:
  plex_server:
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM} # Plex Claim Token for server registration
      - ADVERTISE_IP=${ADVERTISE_IP} # Optional: Advertise server IP
      - PLEX_PASS=${PLEX_PASS} # Optional: Plex Pass (if applicable)
    hostname: <HOSTNAME>
    volumes:
      - ${DOCKERDATA}/hosting/plex:/config
      - ${DOCKERDATA}/hosting/plex/temp:/transcode
      - ${MEDIA}:/media
    image: plexinc/pms-docker
networks: {}
