x-variables:
  PUID: 1000                      # User ID for permissions
  PGID: 1000                      # Group ID for permissions
  TZ: Etc/UTC                     # Timezone
  DUPLICATI_PORT: 8200            # Port for the Duplicati web UI
  DUPLICATI_CONFIG: ./duplicati/config
  BACKUP_SOURCE: ./dockerdata     # Directory containing Docker configs and data
  BACKUP_DEST: ./duplicati/backups

services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - "${DUPLICATI_PORT}:8200"
    volumes:
      - "${DUPLICATI_CONFIG}:/config"
      - "${BACKUP_SOURCE}:/source:ro"
      - "${BACKUP_DEST}:/backups"
    restart: unless-stopped