#!/bin/bash

# Generate .env file
cat <<EOF > .env
PUID=$(id -u)                  # Get the current user's UID
PGID=$(id -g)                  # Get the current user's GID
TZ=$(cat /etc/timezone 2>/dev/null || echo "Etc/UTC") # Get the system timezone
DOMAIN=david.lan               # Set your domain name
HOSTNAME=$(hostname)           # Get the system hostname
DOCKER_SOCK=/var/run/docker.sock
DOCKERDATA=./dockerdata
MEDIA=./media
TORRENTS=./torrents

# ID and Tokens
VAULTWARDEN_ADMIN_TOKEN=your_secure_admin_token
TRAEFIK_ACME_EMAIL=mail@davidlan.xyz

# Ports
PORTAINER_PORT=9000
PORTAINER_AGENT_PORT=9001
OVERSEERR_PORT=5055
SONARR_PORT=8989
RADARR_PORT=7878
PROWLARR_PORT=9696
MYLAR_PORT=8090
BAZARR_PORT=6767
LAZYLIBRARIAN_PORT=5299
LIDARR_PORT=8686
WHISPARR_PORT=6969
JELLYFIN_PORT=8096
PLEX_PORT=32400
AUDIOBOOKSHELF_PORT=13378
STIRLINGPDF_PORT=5060
TRAEFIK_HTTP_PORT=80
TRAEFIK_HTTPS_PORT=443
TRAEFIK_DASHBOARD_PORT=8088
FILEZILLA_PORT=3010
NETDATA_PORT=19999
SPEEDTEST_PORT=8765
UPTIME_KUMA_PORT=3011
VAULTWARDEN_PORT=8093
HEIMDALL_PORT=3002
HOMEPAGE_PORT=3003
NGINX_HTTP_PORT=8080
NGINX_HTTPS_PORT=8443
EOF

echo ".env file generated successfully!"