networks:
  default:
    name: testing
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "${JELLYFIN_PORT}:${JELLYFIN_PORT}"  # HTTP port for web UI
      - "${JELLYFIN_HTTPS_PORT}:${JELLYFIN_HTTPS_PORT}"  # HTTPS port for web UI (optional)
    volumes:
      - ${DOCKERDATA}/hosting/jellyfin:/config
      - ${MEDIA}:/media
      - ${TORRENTS}:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.david.lan`)"
      - "traefik.http.routers.jellyfin.entrypoints=web,websecure"
      - "traefik.http.routers.jellyfin.tls=true"
    #  - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: always
    ports:
      - "${PLEX_PORT}:${PLEX_PORT}"  # Plex web UI
    volumes:
      - ${DOCKERDATA}/hosting/plex:/config
      - ${MEDIA}:/media
      - ${TORRENTS}:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}       # Plex Claim Token for server registration
      - ADVERTISE_IP=${ADVERTISE_IP}  # Optional: Advertise server IP
      - PLEX_PASS=${PLEX_PASS}        # Optional: Plex Pass (if applicable)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"

  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: always
    ports:
      - "${AUDIOBOOKSHELF_PORT}:80"  # Audiobookshelf web UI
    volumes:
      - ${DOCKERDATA}/hosting/audiobookshelf:/config
      - ${MEDIA}/audiobooks:/audiobooks
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.${DOMAIN}`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=myresolver"

  stirling_pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirlingpdf
    restart: always
    ports:
      - 5050:5050  # Stirling PDF web UI
    volumes:
      - ${DOCKERDATA}/hosting/stirlingpdf:/config
      - ${MEDIA}/documents:/pdfs
      - ${DOCKERDATA}/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${DOCKERDATA}/StirlingPDF/extraConfigs:/configs
      - ${DOCKERDATA}/StirlingPDF/customFiles:/customFiles/
      - ${DOCKERDATA}/StirlingPDF/logs:/logs/
      - ${DOCKERDATA}/StirlingPDF/pipeline:/pipeline/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirlingpdf.rule=Host(`stirlingpdf.${DOMAIN}`)"
      - "traefik.http.routers.stirlingpdf.entrypoints=web"
      - "traefik.http.routers.stirlingpdf.tls=true"
    #  - "traefik.http.routers.stirlingpdf.tls.certresolver=myresolver"
