services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"  # HTTP port for web UI
      - "8920:8920"  # HTTPS port for web UI (optional)
    volumes:
      - ./dockerdata/hosting/jellyfin:/config
      - ./media:/media
      - ./torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ .Name }}.rule=Host(`{{ .Name }}.${DOMAIN}`)"
      - "traefik.http.routers.{{ .Name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ .Name }}.tls=true"
      - "traefik.http.routers.{{ .Name }}.tls.certresolver=myresolver"

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: always
    ports:
      - "32400:32400"  # Plex web UI
    volumes:
      - ./dockerdata/hosting/plex:/config
      - ./media:/media
      - ./torrents:/downloads
     environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ .Name }}.rule=Host(`{{ .Name }}.${DOMAIN}`)"
      - "traefik.http.routers.{{ .Name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ .Name }}.tls=true"
      - "traefik.http.routers.{{ .Name }}.tls.certresolver=myresolver"

  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: always
    ports:
      - "13378:13378"  # Audiobookshelf web UI
    volumes:
      - ./dockerdata/hosting/audiobookshelf:/config
      - ./media/audiobooks:/audiobooks
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ .Name }}.rule=Host(`{{ .Name }}.${DOMAIN}`)"
      - "traefik.http.routers.{{ .Name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ .Name }}.tls=true"
      - "traefik.http.routers.{{ .Name }}.tls.certresolver=myresolver"

  stirling_pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirlingpdf
    restart: always
    ports:
      - "5050:5050"  # Stirling PDF web UI
    volumes:
      - ./dockerdata/hosting/stirlingpdf:/config
      - ./media/documents:/pdfs
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ .Name }}.rule=Host(`{{ .Name }}.${DOMAIN}`)"
      - "traefik.http.routers.{{ .Name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ .Name }}.tls=true"
      - "traefik.http.routers.{{ .Name }}.tls.certresolver=myresolver"