entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    tls:
      certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: "${TRAEFIK_ACME_EMAIL}" # Email for Let's Encrypt notifications
      storage: "/letsencrypt/acme.json" # File to store certificates
      httpChallenge:
        entryPoint: web # Use the web entry point for HTTP-01 challenge

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true