# traefik

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/traefik.yml" # Load static config from file
      - "--api.dashboard=true" # Enable Traefik dashboard
      - "--log.level=INFO" # Optional: Set log level
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "${TRAEFIK_DASHBOARD_PORT}:8081" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Required for Docker provider
      - ./selfsigned.crt:/certs/selfsigned.crt
      - ./selfsigned.key:/certs/selfsigned.key
      - ./traefik.yml:/etc/traefik/traefik.yml # Mount the static config file
    environment:
      - TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"

  backend:
    image: nginx:latest
    container_name: nginx-backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    tls:
      certificates:
        - certFile: "/certs/selfsigned.crt"
          keyFile: "/certs/selfsigned.key"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true