# https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/

services:
  
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"   # Traefik will listen on port 8080 by default for API request.
      - "--providers.docker=true"     # Enabling Docker provider
      - "--providers.docker.exposedbydefault=false"     # Do not expose containers unless explicitly told so; TRUE=exposed
      - "--entryPoints.web.address=:80" # Traefik will listen to incoming request on the port 80 (HTTP)
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"     # Explicitly tell Traefik to expose this container
      - "traefik.http.routers.whoami.rule=Host(`david.lan/whoami`)"     # The domain the service will respond to
      - "traefik.http.routers.whoami.entrypoints=web"     # Allow request only from the predefined entry point named "web"