entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    tls:
      certificates:
        - certFile: "dockerdata/certs/selfsigned.crt"
          keyFile: "dockerdata/certs/selfsigned.key"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true