version: '3.7'
services:
  server:
    image: >-
      homeassistant/home-assistant:2025.5.0@sha256:ffb0dfdb5558c7a702fffa23e207ec0e4e1adfb25f3f804fa2dde18689dfef8a
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/home/Downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro
    container_name: home-assistant_server_1
