services:
  nginx:
    image: nginx:latest
    container_name: nginx_test
    networks:
      - testing
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-http.rule=Host(`nginx_test.david.lan`)
      - traefik.http.routers.nginx-http.rule=Host(`nginx_test.d0q9nlblxo.d.firewalla.org`)
      - traefik.http.routers.nginx-http.entrypoints=web
    restart: unless-stopped  
networks:
      testing:
        external: true
      