services:
  nginx:
    image: nginx:latest
    container_name: nginx_test
    networks:
      - testing
    labels:
      - traefik.enable=true
      - >
        traefik.http.routers.nginx-http.rule=
        Host(`nginx.davidlan.local`) ||
        Host(`server.local`) && PathPrefix(`/nginx`) ||
        Host(`server.local`) && PathPrefix(`/nginx`) ||
       # Host(`davidlan.local`) ||
      - traefik.http.routers.nginx-http.entrypoints=web
    restart: unless-stopped  
networks:
      testing:
        external: true
