# done with video here: https://www.youtube.com/watch?v=-hfejNXqOzA
---
services:
  traefik:
    image: traefik:latest
    container_name: traefik_test
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443" # HTTPS port
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config/traefik.yaml:/traefik.yaml:ro
    restart: unless-stopped
    networks:
      - testing
    
networks:
  testing:
    driver: bridge