# done with video here: https://www.youtube.com/watch?v=-hfejNXqOzA
---
services:
  traefik:
    image: traefik:latest
    container_name: traefik_test
    command:
      - "--api.insecure=true" # Enable the Traefik dashboard
      - "--providers.docker=true" # Enable Docker provider
      - "--entrypoints.web.address=:80" # HTTP entrypoint
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint
    ports:
      - "80:80" # Map HTTP traffic to port 8080 on the host
      - "443:443" # Map HTTPS traffic to port 8443 on the host
      - "8081:8080" # Map Traefik dashboard to port 8081 on the host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config/traefik.yaml:/traefik.yaml:ro
    restart: unless-stopped
    networks:
      - testing    

  nginx:
    image: nginx:latest
    container_name: nginx_test
    networks:
      - testing
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx_test-http.rule= Host(`nginx.david.lan`) 
      - traefik.http.routers.nginx_test-http.entrypoints=web
    restart: unless-stopped

networks:
  testing:
    name: testing
    driver: bridge
