global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :8080
  websecure:
    address: :8443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  routers:
    wildcard-router:
      rule: "Host(`*.david.lan`)"
      service: wildcard-service
      entryPoints:
        - web
        - websecure
  services:
    wildcard-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"  # Adjust with your app's internal URL