global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :8080
  websecure:
    address: :8443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
