global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"  # Traefik listens on port 80 for HTTP
  websecure:
    address: ":443"  # Traefik listens on port 443 for HTTPS

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  routers:
    wildcard-router:
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.david.lan`)"  # Wildcard matching for any subdomain
      service: wildcard-service
      entryPoints:
        - web
        - websecure
  